- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        state: present
        name:
          - systemd-swap
          - grub-btrfs
          - owncloud-client
          - nextcloud-client
          - mate-calc
          - discord
          - vlc
          - onlyoffice-desktopeditors
          - chromium
          - firefox
          - tor
          - torbrowser-launcher
          - intellij-idea-community-edition
          - pycharm-community-edition
          - eric
          - code
          - qtcreator
          - spyder
          - geany
          - geany-plugins
          - texstudio
          - okteta
          - go
          - go-tools
          - rust
          - jdk11-openjdk
          - openjdk11-src
          - openjdk11-doc
          - java11-openjfx
          - java11-openjfx-doc
          - java11-openjfx-src
          - nodejs-lts-erbium
          - npm
          - base-devel
          - gdb
          - cmake
          - gitg
          - git-lfs
          - git
          - tk
          - ipcalc
          - curl
          - wget
          - helm
          - kubectl
          - kubectx
          - docker
          - docker-compose
          - remmina
          - freerdp
          - libvncserver
          - nxproxy
          - spice-gtk
          - telepathy-glib
          - xorg-server-xephyr
          - xonsh
          - python-prompt_toolkit
          - xca
          - keepassxc
          - seahorse
          - veracrypt
          - virtualbox
          - qt5ct
          - qt5-styleplugins
          - yad
          - albert
          - android-file-transfer
          - gnome-disk-utility
          - dia
          - backintime
          - kompare
          - meld
          - python-keyring
          - etcher
          - filezilla
          - tilix
          - bind
          - bleachbit
          - snapper-gui
          - filelight
          - gimp
          - inkscape
          - ttf-font-awesome
          - gcolor2
          - print-manager
          - system-config-printer
