# Top

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# Environment
[[ -f ~/.profile ]] && . ~/.profile

autoload -Uz compinit
compinit

# ZSH built in autocomplete
zstyle ':completion:*' menu select

# ZSH autocomplete plugin
zstyle ':autocomplete:*' list-lines 30
zstyle ':autocomplete:history-search:*' list-lines 30
zstyle ':autocomplete:history-incremental-search-*:*' list-lines 30
zstyle ':autocomplete:*' min-delay 1.0
zstyle ':autocomplete:*' add-ending no

export GLOBAL_ZSH_PLUGIN_PATH=/usr/share/zsh/plugins
export GLOBAL_ZSH_PLUGINS=(zsh-autosuggestions zsh-syntax-highlighting)

for plugin in $GLOBAL_ZSH_PLUGINS
do
    pluginfile=$GLOBAL_ZSH_PLUGIN_PATH/$plugin/$plugin.plugin.zsh
    [[ -f $pluginfile ]] && source $pluginfile

    # Fallback
    pluginfile=$GLOBAL_ZSH_PLUGIN_PATH/$plugin/$plugin.zsh
    [[ -f $pluginfile ]] && source $pluginfile
done

source $GLOBAL_ZSH_PLUGIN_PATH/goto.sh

export CUSTOM_ZSH_PLUGIN_PATH=~/.zsh/plugins
export CUSTOM_ZSH_PLUGINS=()

for plugin in $CUSTOM_ZSH_PLUGINS
do
    source $CUSTOM_ZSH_PLUGIN_PATH/$plugin/$plugin.zsh
done

# Plugin updater
UPDATABLE_GLOBAL_ZSH_PLUGINS=(zsh-autocomplete)
UPDATABLE_CUSTOM_ZSH_PLUGINS=()

update-plugins() {
    for plugin in $UPDATABLE_GLOBAL_ZSH_PLUGINS
    do
        pluginpath="$GLOBAL_ZSH_PLUGIN_PATH/$plugin"
        echo "Updating $pluginpath ($plugin) ..."
        sudo git -C $pluginpath pull
    done

    for plugin in $UPDATABLE_CUSTOM_ZSH_PLUGINS
    do
        pluginpath="$CUSTOM_ZSH_PLUGIN_PATH/$plugin"
        echo "Updating $pluginpath ($plugin) ..."
        sudo git -C $pluginpath pull
    done
}

# mode
bindkey -e
#bindkey -v
export KEYTIMEOUT=1

# Keybindings
bindkey "^a" beginning-of-line
bindkey "^e" end-of-line
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# Edit line in vim with ctrl-e
autoload edit-command-line
zle -N edit-command-line
bindkey "^l" edit-command-line

# History configuration
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=1000
export SAVEHIST=5000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data

clear_history() {
    echo "" > $HISTFILE
    history -p
}

# Autocorrection
alias cp='nocorrect cp'
alias ebuild='nocorrect ebuild'
alias gist='nocorrect gist'
alias heroku='nocorrect heroku'
alias hpodder='nocorrect hpodder'
alias man='nocorrect man'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'
alias mysql='nocorrect mysql'
alias sudo='nocorrect sudo'

setopt correct_all

# Directory config
## Changing/making/removing directory
setopt auto_pushd
setopt pushd_ignore_dups
setopt pushdminus

# Alias config
[[ -f ~/.aliases ]] && . ~/.aliases

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Custom conf
[[ -f ~/.zshrc_custom ]] && . ~/.zshrc_custom
