---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: prepare install virtualization
      ansible.builtin.command: pamac install --no-confirm iptables-nft

    - name: install virtualization
      ansible.builtin.package:
        state: present
        name:
          - dkms
          - virtualbox
          - virtualbox-guest-iso
          - libvirt
          - qemu-emulators-full
          - qemu-ui-curses
          - qemu-ui-opengl
          - qemu-ui-spice-app
          - qemu-ui-sdl
          - qemu-ui-gtk
          - qemu-arch-extra
          - qemu-block-iscsi
          - qemu-block-gluster
          - libvirt-storage-iscsi-direct
          - radvd
          - ebtables
          - open-iscsi
          - virt-manager
          - edk2-ovmf
          - lxd
          - lxc

    - name: enable libvirt service
      ansible.builtin.service:
        name: libvirtd
        enabled: true
        state: started

    - name: add user to libvirt
      ansible.builtin.user:
        name: "{{ config_user }}"
        append: true
        groups: libvirt
