---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install system tools
      ansible.builtin.package:
        state: present
        name:
          - arch-install-scripts
          - shim
          - mtools
          - gpart
          - gparted
          - udftools
          - gnome-firmware
          - gnome-disk-utility
          - bleachbit
          - baobab
          - xfce4-taskmanager
          - xcape
          - apparmor
          - python-notify2

    - name: install Firewall (Portmaster)
      ansible.builtin.command: pamac install --no-confirm portmaster-stub-bin

    - name: enable portmaster service
      ansible.builtin.service:
        name: portmaster
        enabled: true
        state: started

    - name: install Arronax
      ansible.builtin.command: pamac install --no-confirm arronax

    - name: install Gnome logs
      when: "not desktop is undefined and desktop == 'xfce'"
      ansible.builtin.package:
        state: present
        name:
          - gnome-logs

    - name: prepare install exFAT progs
      ansible.builtin.command: pamac install --no-confirm exfatprogs

    - name: install preload
      ansible.builtin.command: pamac install --no-confirm preload

    - name: install earlyoom
      ansible.builtin.package:
        state: present
        name:
          - earlyoom
          - systembus-notify

    - name: enable earlyoom service
      ansible.builtin.service:
        name: earlyoom
        enabled: true
        state: started

    - name: install Systemd swap
      ansible.builtin.package:
        state: present
        name:
          - systemd-swap

    - name: enable systemd-swap service
      ansible.builtin.service:
        name: systemd-swap
        enabled: true
        state: started
