---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install Java SDK
      ansible.builtin.package:
        state: present
        name:
          - jdk8-openjdk
          - openjdk8-src
          - openjdk8-doc
          
          - jdk11-openjdk
          - openjdk11-src
          - openjdk11-doc
          
          - jdk17-openjdk
          - openjdk17-src
          - openjdk17-doc
          
          - jdk-openjdk
          - openjdk-src
          - openjdk-doc
          
          - ant
          - maven
          - gradle

    - name: install PHP
      package:
        state: present
        name:
          - composer
          - php
          - xdebug

    - name: install Node.js latest
      package:
        state: present
        name:
          - nodejs
          - npm
          - yarn

    - name: install Go
      package:
        state: present
        name:
          - gcc-go
          - go-tools

    - name: install Rustup
      package:
        state: present
        name:
          - rustup
          - lldb

    - name: install D
      package:
        state: present
        name:
          - dmd
          - dtools
