---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install XFCE
      when: "not desktop is undefined and desktop == 'xfce'"
      ansible.builtin.package:
        state: present
        name:
          - xfce4
          - light-locker
          - network-manager-applet
          - xfce4-battery-plugin
          - xfce4-clipman-plugin
          - xfce4-cpufreq-plugin
          - xfce4-cpugraph-plugin
          - xfce4-dict
          - xfce4-diskperf-plugin
          - xfce4-fsguard-plugin
          - xfce4-genmon-plugin
          - xfce4-mailwatch-plugin
          - xfce4-mount-plugin
          - xfce4-mpc-plugin
          - xfce4-netload-plugin
          - xfce4-notes-plugin
          - xfce4-notifyd
          - xfce4-screenshooter
          - xfce4-sensors-plugin
          - xfce4-smartbookmark-plugin
          - xfce4-systemload-plugin
          - xfce4-time-out-plugin
          - xfce4-timer-plugin
          - xfce4-verve-plugin
          - xfce4-terminal
          - xfce4-wavelan-plugin
          - xfce4-weather-plugin
          - xfce4-whiskermenu-plugin
          - xfce4-xkb-plugin
          - xfce4-pulseaudio-plugin
          - pavucontrol
          - ristretto
          - parole
          - catfish

    - name: install Thunar file manager
      ansible.builtin.package:
        state: present
        name:
          - thunar
          - thunar-volman
          - thunar-archive-plugin

    - name: install Xfdashboard
      ansible.builtin.command: pamac install --no-confirm xfdashboard
