---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install themes
      ansible.builtin.package:
        name:
          - papirus-icon-theme
          - gnome-backgrounds
          - kvantum

    - name: install Greybird theme
      ansible.builtin.command: pamac install --no-confirm xfce-theme-greybird

    - name: install Qt5/6 configuration tool
      ansible.builtin.package:
        state: present
        name:
          - qt5ct
          - qt6ct
          
    - name: install fonts
      ansible.builtin.package:
        state: present
        name:
          - noto-fonts-emoji
          - ttf-font-awesome
          - ttf-jetbrains-mono-nerd

    - name: install nerd fonts
      ansible.builtin.file:
        path: /usr/local/share/fonts
        state: directory

    - name: install nerd fonts
      ansible.builtin.unarchive:
        remote_src: true
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip
        dest: /usr/local/share/fonts

    - name: install MacOS cursor
      ansible.builtin.unarchive:
        remote_src: true
        src: https://github.com/ful1e5/apple_cursor/releases/download/v1.2.3/macOSMonterey.tar.gz
        dest: /usr/share/icons
        
    - name: Set default cursor
      ansible.builtin.copy:
        src: ../files/cursor.theme
        dest: /usr/share/icons/default/index.theme
        force: true
      when: not copy_configs is undefined and copy_configs == "true"

    - name: install theme dependencies
      ansible.builtin.package:
        state: present
        name:
          - sassc
          - optipng
          - inkscape

    - name: clone Mojave GTK theme
      ansible.builtin.git:
        repo: https://github.com/vinceliuice/Mojave-gtk-theme.git
        dest: /tmp/Mojave-gtk-theme
        version: 2023-08-04

    - name: install Mojave GTK theme
      ansible.builtin.command: 
        cmd: ./install.sh
        chdir: /tmp/Mojave-gtk-theme

    - name: clone Mojave KDE theme
      ansible.builtin.git:
        repo: https://github.com/vinceliuice/McMojave-kde.git
        dest: /tmp/McMojave-kde

    - name: copy McMojave KDE Kvantum theme
      become_user: "{{ config_user }}"
      ansible.builtin.copy:
        src: /tmp/McMojave-kde/Kvantum
        dest: ~/.config/

    - name: patch Kvantum themes
      become_user: "{{ config_user }}"
      ansible.builtin.command: /bin/bash -c 'sed -i "s/composite=true/composite=false/g" ~/.config/Kvantum/*/*.kvconfig'

    - name: clone Whitesur Icon theme
      ansible.builtin.git:
        repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
        dest: /tmp/WhiteSur-icon-theme
        version: 2023-01-08

    - name: install Whitesur Icon theme
      ansible.builtin.command:
        cmd: ./install.sh --black
        chdir: /tmp/WhiteSur-icon-theme

    - name: patch Whitesur Icon theme
      ansible.builtin.command: sed -i "s/Inherits=hicolor/Inherits=Papirus-Light,hicolor/g" /usr/share/icons/WhiteSur/index.theme

    - name: patch Whitesur Icon theme
      ansible.builtin.command: sed -i "s/Inherits=hicolor/Inherits=Papirus-Dark,hicolor/g" /usr/share/icons/WhiteSur-dark/index.theme

    - name: install Plank themes
      ansible.builtin.copy:
        src: /usr/share/themes/Mojave-Light/plank/
        dest: /usr/share/plank/themes/OSX

    - name: copy themes
      ansible.builtin.copy:
        src: ../files/themes/
        dest: /usr/share/themes/

    - name: install Plank themes
      ansible.builtin.copy:
        src: /usr/share/themes/Mojave-Dark/plank/
        dest: /usr/share/plank/themes/OSX-dark

    - name: clone Grub Theme
      ansible.builtin.git:
        repo: https://github.com/vinceliuice/grub2-themes.git
        dest: /tmp/grub2-themes

    - name: Install Grub theme
      ansible.builtin.command: /tmp/grub2-themes/install.sh -b -t tela
      ignore_errors: true

    - name: copy theme profiles
      become_user: "{{ config_user }}"
      ansible.builtin.copy:
        src: ../files/theme-profiles/
        dest: ~/.theme-profiles
        force: true
      when: not copy_configs is undefined and copy_configs == "true"

    - name: link default light theme
      become_user: "{{ config_user }}"
      ansible.builtin.file:
        src: ~/.theme-profiles/MojaveWin-light
        dest: ~/.theme-profiles/default-light-theme
        state: link
        force: false

    - name: link default dark theme
      become_user: "{{ config_user }}"
      ansible.builtin.file:
        src: ~/.theme-profiles/MojaveWin-dark
        dest: ~/.theme-profiles/default-dark-theme
        state: link
        force: false
