---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: copy Pamac config
      copy:
        src: ../files/pamac.conf
        dest: /etc/
      when: not copy_configs is undefined and copy_configs == "true"

    - name: install network utils
      package:
        state: present
        name:
          - avahi
          - networkmanager
          - networkmanager-openconnect
          - networkmanager-openvpn
          - networkmanager-pptp
          - networkmanager-vpnc
          - mosh
          - sshfs
          - netstat-nat
          - traceroute
          - bind

    - name: install system tools
      package:
        state: present
        name:
          - arch-install-scripts
          - shim
          - mtools
          - gpart
          - gparted
          - udftools
          - gnome-firmware
          - gnome-disk-utility

    - name: prepare install exFAT progs
      command: pamac install --no-confirm exfatprogs

    - name: install XFCE
      package:
        state: present
        name:
          - xfce4
          - light-locker
          - network-manager-applet
          - menulibre
          - xfce4-battery-plugin
          - xfce4-clipman-plugin
          - xfce4-cpufreq-plugin
          - xfce4-cpugraph-plugin
          - xfce4-dict
          - xfce4-diskperf-plugin
          - xfce4-fsguard-plugin
          - xfce4-genmon-plugin
          - xfce4-mailwatch-plugin
          - xfce4-mount-plugin
          - xfce4-mpc-plugin
          - xfce4-netload-plugin
          - xfce4-notes-plugin
          - xfce4-notifyd
          - xfce4-screenshooter
          - xfce4-sensors-plugin
          - xfce4-smartbookmark-plugin
          - xfce4-systemload-plugin
          - xfce4-taskmanager
          - xfce4-time-out-plugin
          - xfce4-timer-plugin
          - xfce4-verve-plugin
          - xfce4-wavelan-plugin
          - xfce4-weather-plugin
          - xfce4-whiskermenu-plugin
          - xfce4-xkb-plugin
          - xfce4-pulseaudio-plugin
          - pavucontrol

    - name: install base dev tools
      package:
        state: present
        name:
          - base-devel
          - clang
          - llvm
          - lld
          - lldb
          - gdb
          - cmake
          - ninja
          - samurai
          - gitg
          - git-lfs
          - git
          - tk
          - python3
          - pypy3
          - cloc
          - gvim
          - python-pip
          - python-virtualenv

    - name: install shells + terminals
      package:
        state: present
        name:
          - zsh
          - zsh-autosuggestions
          - zsh-completions
          - zsh-doc
          - zsh-syntax-highlighting
          - zsh-history-substring-search
          - zsh-theme-powerlevel10k
          - zshdb
          - fish
          - dash
          - shellcheck
          - lsd
          - neofetch
          - terminator
          - python-pygments

    - name: link Dash in /bin
      file:
        src: /usr/bin/dash
        dest: /bin/sh
        state: link
        force: true

    - name: install ZSH realtime auto complete
      git:
        repo: https://github.com/marlonrichert/zsh-autocomplete.git
        dest: /usr/share/zsh/plugins/zsh-autocomplete

    - name: install PyPy 3 pip
      command: /opt/pypy3/bin/pypy3 -m ensurepip

    - name: install Xonsh
      pip:
        virtualenv: /opt/xonsh
        name:
          - xonsh[full]
          - setproctitle
          - jedi
          - pip

    - name: link Xonsh
      file:
        src: /opt/xonsh/bin/xonsh
        dest: /usr/local/bin/xonsh
        state: link

    - name: link Xonsh in /usr/bin
      file:
        src: /usr/local/bin/xonsh
        dest: /usr/bin/xonsh
        state: link

    - name: install goto
      get_url:
        url: https://raw.githubusercontent.com/iridakos/goto/master/goto.sh
        dest: /usr/share/zsh/plugins/goto.sh
        owner: root
        group: root
        mode: 774
        force: true

    - name: install IDEs
      package:
        state: present
        name:
          - intellij-idea-community-edition
          - pycharm-community-edition
          - qtcreator
          - geany
          - geany-plugins
          - texstudio
          - texlive-latexextra
          - texlive-langextra
          - texlive-humanities
          - texlive-games
          - texlive-formatsextra
          - texlive-fontsextra
          - okteta
          - mysql-workbench
          - mariadb-clients
          - pgadmin4
          - sqlitebrowser
          - kexi

    - name: install Eric IDE
      pip:
        virtualenv: /opt/eric6
        name:
          - eric-ide
          - pip

    - name: install Spyder IDE
      pip:
        virtualenv: /opt/spyder
        name:
          - spyder
          - pip

    - name: install VS Code
      command: pamac install --no-confirm visual-studio-code-bin

    - name: install VS Code plugin
      become_user: "{{ config_user }}"
      command: "/usr/bin/code --install-extension {{ item }}"
      when: "config_user != 'root'"
      loop:
        - ms-azuretools.vscode-docker
        - ms-kubernetes-tools.vscode-kubernetes-tools
        - ms-vscode-remote.remote-containers
        - mindaro.mindaro
        - ms-vsliveshare.vsliveshare-pack
        - rust-lang.rust
        - golang.go
        - vscjava.vscode-java-pack
        - ms-python.python
        - ms-pyright.pyright
        - octref.vetur
        - dbaeumer.vscode-eslint
        - jnoortheen.xonsh
        - mtxr.sqltools
        - redhat.ansible
        - ms-vscode.cpptools-extension-pack
        - thenouillet.symfony-vscode
        - mblode.twig-language-2
        - msjsdiag.debugger-for-chrome
        - firefox-devtools.vscode-firefox-debug
        - gruntfuggly.todo-tree
        - christian-kohler.path-intellisense
        - vscode-icons-team.vscode-icons
        - oderwat.indent-rainbow
        - eamodio.gitlens

    - name: install Java SDK
      package:
        state: present
        name:
          - jdk8-openjdk
          - jre8-openjdk
          - jre8-openjdk-headless
          - jdk11-openjdk
          - openjdk11-src
          - openjdk11-doc
          - java11-openjfx
          - java11-openjfx-doc
          - java11-openjfx-src
          - jdk-openjdk
          - openjdk-src
          - openjdk-doc
          - java-openjfx
          - java-openjfx-doc
          - java-openjfx-src
          - ant
          - maven
          - gradle

    - name: install PHP
      package:
        state: present
        name:
          - composer
          - php
          - php7
          - xdebug

    - name: install Node.js 14
      package:
        state: present
        name:
          - nodejs-lts-fermium
          - npm

    - name: install Go
      package:
        state: present
        name:
          - go
          - go-tools

    - name: install Rustup
      package:
        state: present
        name:
          - rustup
          - lldb

    - name: install simple tools
      package:
        state: present
        name:
          - ipcalc
          - curl
          - wget

    - name: install Docker and Kubernetes tools
      package:
        state: present
        name:
          - helm
          - kubectl
          - kubectx
          - docker
          - docker-compose

    - name: add user to Docker
      user:
        name: "{{ config_user }}"
        append: true
        groups: docker

    - name: enable Docker service
      service:
        name: docker
        enabled: true

    - name: install Remmina
      package:
        state: present
        name:
          - remmina
          - freerdp
          - libvncserver
          - nxproxy
          - spice-gtk
          - telepathy-glib
          - xorg-server-xephyr

    - name: install crypto tools
      package:
        state: present
        name:
          - xca
          - keepassxc
          - xclip
          - wl-clipboard
          - seahorse
          - veracrypt

    - name: install browsers
      package:
        state: present
        name:
          - chromium
          - firefox
          - tor
          - torbrowser-launcher

    - name: prepare install virtualization
      command: pamac install --no-confirm iptables-nft

    - name: install virtualization
      package:
        state: present
        name:
          - dkms
          - virtualbox
          - virtualbox-host-dkms
          - virtualbox-guest-iso
          - libvirt
          - qemu
          - qemu-arch-extra
          - qemu-block-iscsi
          - qemu-block-rbd
          - libvirt-storage-iscsi-direct
          - libvirt-storage-rbd
          - radvd
          - ebtables
          - open-iscsi
          - virt-manager
          - edk2-ovmf
          - lxd
          - lxc

    - name: enable libvirt service
      service:
        name: libvirtd
        enabled: true
        state: started

    - name: add user to libvirt
      user:
        name: "{{ config_user }}"
        append: true
        groups: libvirt

    - name: install Qt5 configuration tool
      package:
        state: present
        name:
          - qt5ct
          - qt5-styleplugins

    - name: install printing tools
      package:
        state: present
        name:
          - print-manager
          - system-config-printer

    - name: enable CUPS service
      service:
        name: cups
        enabled: true
        state: started

    - name: install graphics tools
      package:
        state: present
        name:
          - dia
          - gimp
          - inkscape
          - gcolor2
          - krita
          - kseexpr
          - kimageformats
          - darktable
          - rawtherapee
          - qt5-imageformats
          - digikam
          - spectacle
          - blender
          - drawing

    - name: install backup tools
      package:
        state: present
        name:
          - snapper
          - snapper-gui
          - backintime
          - kompare
          - meld
          - python-keyring
          - timeshift
          - grub-btrfs

    - name: install preload
      package:
        state: present
        name:
          - preload

    - name: install earlyoom
      package:
        state: present
        name:
          - earlyoom
          - systembus-notify

    - name: enable earlyoom service
      service:
        name: earlyoom
        enabled: true
        state: started

    - name: install Systemd swap
      package:
        state: present
        name:
          - systemd-swap

    - name: configure ZRAM
      copy:
        src: ../files/swap.conf.d
        dest: /etc/systemd
      when: not copy_configs is undefined and copy_configs == "true"

    - name: install multimedia packages
      package:
        state: present
        name:
          - vlc
          - lmms
          - pitivi
          - openshot
          - flowblade
          - obs-studio
          - audacity
          - vokoscreen
          - gnome-sound-recorder
          - ristretto
          - parole
          - xfburn
          - cheese

    - name: install dockbars and launchers
      package:
        state: present
        name:
          - plank
          - synapse
          - muparser

    - name: install albert launcher
      command: pamac install --no-confirm albert-bin

    - name: install albert launcher
      command: pamac install --no-confirm xfdashboard

    - name: install themes
      package:
        name:
          - xfce-theme-greybird
          - papirus-icon-theme
          - kvantum-qt5

    - name: install fonts
      package:
        state: present
        name:
          - noto-fonts-emoji
          - ttf-font-awesome

    - name: install nerd fonts
      file:
        path: /usr/local/share/fonts
        state: directory

    - name: install nerd fonts
      unarchive:
        remote_src: true
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/DejaVuSansMono.zip
        dest: /usr/local/share/fonts

    - name: install theme dependencies
      package:
        state: present
        name:
          - sassc
          - optipng
          - inkscape

    - name: clone Mojave GTK theme
      git:
        repo: https://github.com/vinceliuice/Mojave-gtk-theme.git
        dest: /tmp/Mojave-gtk-theme

    - name: install Mojave GTK theme
      command: /tmp/Mojave-gtk-theme/install.sh

    - name: clone Whitesur GTK theme
      git:
        repo: https://github.com/vinceliuice/WhiteSur-gtk-theme.git
        dest: /tmp/WhiteSur-gtk-theme

    - name: install Whitesur GTK theme
      command: /tmp/WhiteSur-gtk-theme/install.sh --color light --color dark --theme all --panel-opacity 75 --black

    - name: clone Whitesur Icon theme
      git:
        repo: https://github.com/vinceliuice/WhiteSur-icon-theme.git
        dest: /tmp/WhiteSur-icon-theme

    - name: install Whitesur Icon theme
      command: /tmp/WhiteSur-icon-theme/install.sh --black

    - name: patch Whitesur Icon theme
      command: sed -i "s/Inherits=hicolor/Inherits=Papirus-Light,hicolor/g" /usr/share/icons/WhiteSur/index.theme

    - name: patch Whitesur Icon theme
      command: sed -i "s/Inherits=hicolor/Inherits=Papirus-Dark,hicolor/g" /usr/share/icons/WhiteSur-dark/index.theme

    - name: install Plank themes
      copy:
        src: /usr/share/themes/Mojave-light/plank/
        dest: /usr/share/plank/themes/OSX

    - name: install Plank themes
      copy:
        src: /usr/share/themes/Mojave-dark/plank/
        dest: /usr/share/plank/themes/OSX-dark

    - name: clone Grub Theme
      git:
        repo: https://github.com/vinceliuice/grub2-themes.git
        dest: /tmp/grub2-themes

    - name: Install Grub theme
      command: /tmp/grub2-themes/install.sh -b -t tela
      ignore_errors: true

    - name: install lightdm
      package:
        state: present
        name:
          - lightdm-webkit2-greeter
          - lightdm-webkit-theme-litarvan

    - name: install cloud tools
      package:
        state: present
        name:
          - owncloud-client
          - nextcloud-client

    - name: install office tools
      package:
        state: present
        name:
          - libreoffice-still
          - pstoedit
          - libmythes
          - coin-or-mp
          - beanshell
          - onlyoffice-desktopeditors
          - atril
          - okular
          - khtml
          - chmlib
          - ebook-tools
          - kdegraphics-mobipocket
          - mate-calc
          - simple-scan
          - gnucash
          - engrampa
          - gnome-characters
          - xournalpp

    - name: install other packages
      package:
        state: present
        name:
          - discord
          - yad
          - android-file-transfer
          - etcher
          - filezilla
          - hexchat
          - pidgin
          - bleachbit
          - filelight
          - transmission-gtk
          - ibus-typing-booster
          - gtkhash-thunar
          - variety
          - kdeconnect
          - minetest
          - ventoy
          - redshift
          - gnome-weather
          - gnome-maps
          - ffmpegthumbs

    - name: remove packages
      package:
        state: absent
        name:
          - viewnior
          - mpv
          - audacious
          - clementine
          - galculator
          - galculator-gtk2

    - name: install auto cpu frequence launcher
      command: pamac install --no-confirm auto-cpufreq
          
    - name: enable auto CPU frequence
      service:
        name: auto-cpufreq
        state: started
        enabled: true

    - name: copy user configs
      become_user: "{{ config_user }}"
      copy:
        src: ../files/userconfig/
        dest: ~/.config
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy user configs
      become_user: "{{ config_user }}"
      copy:
        src: ../files/theme-profiles/
        dest: ~/.theme-profiles
        force: false
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy user xonshrc
      become_user: "{{ config_user }}"
      copy:
        src: ../files/xonshrc
        dest: ~/.xonshrc
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy .bashrc
      become_user: "{{ config_user }}"
      copy:
        src: ../files/bashrc
        dest: ~/.bashrc
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy .zshrc
      become_user: "{{ config_user }}"
      copy:
        src: ../files/zshrc
        dest: ~/.zshrc
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy .p10k.zsh
      become_user: "{{ config_user }}"
      copy:
        src: ../files/p10k.zsh
        dest: ~/.p10k.zsh
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy .profile
      become_user: "{{ config_user }}"
      copy:
        src: ../files/profile
        dest: ~/.profile
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy .aliases
      become_user: "{{ config_user }}"
      copy:
        src: ../files/aliases
        dest: ~/.aliases
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy application launchers
      copy:
        src: ../files/applications/
        dest: /usr/local/share/applications

    - name: copy faillock.conf
      copy:
        src: ../files/faillock.conf
        dest: /etc/security/
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy logind.conf
      copy:
        src: ../files/logind.conf
        dest: /etc/systemd/
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy LightDM config
      copy:
        src: ../files/lightdm/
        dest: /etc/lightdm
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy bin
      copy:
        src: ../files/bin/
        dest: /usr/local/bin

    - name: copy themes
      copy:
        src: ../files/themes/
        dest: /usr/share/themes

    - name: set exec permissions
      file:
        path: "{{ item }}"
        mode: "775"
      loop:
        - /usr/local/bin/gufw_icon.sh
        - /usr/local/bin/cht.sh
        - /usr/local/bin/fast-theme-switch.sh
