---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install base dev tools
      package:
        state: present
        name:
          - base-devel
          - gdb
          - cmake
          - gitg
          - git-lfs
          - git
          - tk

    - name: install IDEs
      package:
        state: present
        name:
          - intellij-idea-community-edition
          - pycharm-community-edition
          - eric
          - code
          - qtcreator
          - spyder
          - geany
          - geany-plugins
          - texstudio
          - okteta
          
    - name: install VS Code plugin Python
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-python.python

    - name: install VS Code plugin Anaconda Python
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-python.anaconda-extension-pack

    - name: install VS Code plugin Pyrigt
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-pyright.pyright
      
    - name: install VS Code plugin Docker
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-azuretools.vscode-docker

    - name: install VS Code plugin K8s
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
    
    - name: install VS Code plugin Vetur (Vue.js)
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension octref.vetur
    
    - name: install VS Code plugin ES-Lint
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension dbaeumer.vscode-eslint
    
    - name: install VS Code plugin Lit-HTML
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension runem.lit-plugin

    - name: install VS Code plugin Chrome Debugger
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension msjsdiag.debugger-for-chrome
    
    - name: install VS Code plugin Firefox Debugger
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension firefox-devtools.vscode-firefox-debug
    
    - name: install VS Code plugin TODO
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension gruntfuggly.todo-tree
    
    - name: install VS Code plugin Xonsh
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension jnoortheen.xonsh

    - name: install Java 11 SDK
      package:
        state: present
        name:
          - jdk11-openjdk
          - openjdk11-src
          - openjdk11-doc
          - java11-openjfx
          - java11-openjfx-doc
          - java11-openjfx-src
          - maven
          - gradle

    - name: install Node.js 14
      package:
        state: present
        name:
          - nodejs-lts-fermium
          - npm

    - name: install Go
      package:
        state: present
        name:
          - go
          - go-tools

    - name: install Rust
      package:
        state: present
        name:
          - rust

    - name: install simple tools
      package:
        state: present
        name:
          - ipcalc
          - curl
          - wget
          - bind

    - name: install Docker and Kubernetes tools
      package:
        state: present
        name:
          - helm
          - kubectl
          - kubectx
          - docker
          - docker-compose

    - name: add user to Docker
      user:
        name: "{{ config_user }}"
        append: true
        groups: docker

    - name: enable Docker service
      service:
        name: docker
        enabled: true
        state: started

    - name: install Remmina
      package:
        state: present
        name:
          - remmina
          - freerdp
          - libvncserver
          - nxproxy
          - spice-gtk
          - telepathy-glib
          - xorg-server-xephyr
      
    - name: install Xonsh
      package:
        state: present
        name:
          - xonsh
          - python-prompt_toolkit

    - name: copy xonshrc 
      become_user: "{{ config_user }}"
      copy:
        src: ../files/xonshrc
        dest: ~/.xonshrc

    - name: install crypto tools
      package:
        state: present
        name:
          - xca
          - keepassxc
          - seahorse
          - veracrypt

    - name: install browsers
      package:
        state: present
        name:
          - chromium
          - firefox
          - tor
          - torbrowser-launcher

    - name: install VirtualBox
      package:
        state: present
        name:
          - virtualbox

    - name: install Qt5 configuration tool
      package:
        state: present
        name:
          - qt5ct
          - qt5-styleplugins

    - name: install printing tools
      package:
        state: present
        name:
          - print-manager
          - system-config-printer

    - name: install graphics tools
      package:
        state: present
        name:
          - dia
          - gimp
          - inkscape
          - gcolor2

    - name: install backup tools
      package:
        state: present
        name:
          - snapper
          - snapper-gui
          - backintime
          - kompare
          - meld
          - python-keyring
          - timeshift
          - grub-btrfs

    - name: install Dolphin
      package:
        state: present
        name:
          - dolphin
          - dolphin-plugins

    - name: install Plasma desktop
      package:
        state: present
        name:
          - plasma-desktop

    - name: disable Baloo file indexer
      become_user: "{{ config_user }}"
      command: balooctl disable

    - name: install other packages
      package:
        state: present
        name:
          - systemd-swap
          - owncloud-client
          - nextcloud-client
          - mate-calc
          - discord
          - vlc
          - onlyoffice-desktopeditors
          - yad
          - albert
          - android-file-transfer
          - gnome-disk-utility
          - etcher
          - filezilla
          - tilix
          - bleachbit
          - filelight
          - ttf-font-awesome
          - transmission-gtk
          - noto-fonts-emoji
          - ibus-typing-booster
          - papirus-icon-theme
          - gtkhash-thunar
          - atril
          - engrampa

    - name: copy user configs
      become_user: "{{ config_user }}"
      copy:
        src: ../files/userconfig/
        dest: ~/.config
      when: not copy_config is undefined and copy_config == "true"

    - name: copy application launchers
      copy:
        src: ../files/applications/
        dest: /usr/local/share/applications

    - name: copy bin
      copy:
        src: ../files/bin/
        dest: /usr/local/bin
