---
- ansible.builtin.import_playbook: ./pamac-config.yml
- ansible.builtin.import_playbook: ./install-system-tools.yml
- ansible.builtin.import_playbook: ./install-network-utils.yml
- ansible.builtin.import_playbook: ./install-xfce.yml
- ansible.builtin.import_playbook: ./install-dev-tools.yml
- ansible.builtin.import_playbook: ./install-vscode-plugins.yml
- ansible.builtin.import_playbook: ./install-shells.yml
- ansible.builtin.import_playbook: ./install-language-sdks.yml
- ansible.builtin.import_playbook: ./install-container-tools.yml
- ansible.builtin.import_playbook: ./install-virtualization.yml
- ansible.builtin.import_playbook: ./install-themes.yml
- ansible.builtin.import_playbook: ./install-desktop.yml
- ansible.builtin.import_playbook: ./configure.yml

- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: remove packages
      package:
        state: absent
        name:
          - xterm
          - uxterm
          - viewnior
          - audacious
          - clementine
          - galculator
          - galculator-gtk2
          - gcolor2
          - mousepad
          - xfwm4-themes
