---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install network utils
      package:
        state: present
        name:
          - avahi
          - networkmanager
          - networkmanager-openconnect
          - networkmanager-openvpn
          - networkmanager-pptp
          - networkmanager-vpnc
          
    - name: install XFCE
      package:
        state: present
        name:
          - xfce4
          - light-locker
          - network-manager-applet
          - menulibre
          - xfce4-battery-plugin
          - xfce4-clipman-plugin
          - xfce4-cpufreq-plugin
          - xfce4-cpugraph-plugin
          - xfce4-dict
          - xfce4-diskperf-plugin
          - xfce4-fsguard-plugin
          - xfce4-genmon-plugin
          - xfce4-mailwatch-plugin
          - xfce4-mount-plugin
          - xfce4-mpc-plugin
          - xfce4-netload-plugin
          - xfce4-notes-plugin
          - xfce4-notifyd
          - xfce4-screenshooter
          - xfce4-sensors-plugin
          - xfce4-smartbookmark-plugin
          - xfce4-systemload-plugin
          - xfce4-taskmanager
          - xfce4-time-out-plugin
          - xfce4-timer-plugin
          - xfce4-verve-plugin
          - xfce4-wavelan-plugin
          - xfce4-weather-plugin
          - xfce4-whiskermenu-plugin
          - xfce4-xkb-plugin
          - xfce4-pulseaudio-plugin
          - pavucontrol
    
    - name: install base dev tools
      package:
        state: present
        name:
          - base-devel
          - gdb
          - cmake
          - gitg
          - git-lfs
          - git
          - tk
          - python3
          - pypy3
          - zsh
          - fish
      
    - name: install PyPy 3 pip
      command: /opt/pypy3/bin/pypy3 -m ensurepip

    - name: install Xonsh Python virtual environment
      command: python3 -m venv /opt/xonsh

    - name: install Xonsh Python virtual environment
      command: /opt/xonsh/bin/python3 -m pip install --upgrade pip

    - name: install Xonsh
      command: /opt/xonsh/bin/python3 -m pip install xonsh[full] setproctitle jedi

    - name: install IDEs
      package:
        state: present
        name:
          - intellij-idea-community-edition
          - pycharm-community-edition
          - code
          - qtcreator
          - geany
          - geany-plugins
          - texstudio
          - textlive-latexextra
          - okteta
          - kate
          - mysql-workbench
          - mariadb-clients
          - pgadmin4
          - sqlitebrowser
          - kexi
          
    - name: install VS Code plugin Python
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-python.python

    - name: install VS Code plugin Anaconda Python
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-python.anaconda-extension-pack

    - name: install VS Code plugin Pyrigt
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-pyright.pyright
      
    - name: install VS Code plugin Docker
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-azuretools.vscode-docker

    - name: install VS Code plugin K8s
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
    
    - name: install VS Code plugin Vetur (Vue.js)
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension octref.vetur
    
    - name: install VS Code plugin ES-Lint
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension dbaeumer.vscode-eslint

    - name: install VS Code plugin Chrome Debugger
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension msjsdiag.debugger-for-chrome
    
    - name: install VS Code plugin Firefox Debugger
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension firefox-devtools.vscode-firefox-debug
    
    - name: install VS Code plugin TODO
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension gruntfuggly.todo-tree
    
    - name: install VS Code plugin Xonsh
      become_user: "{{ config_user }}"
      command: /usr/bin/code --install-extension jnoortheen.xonsh

    - name: install Java 11 SDK
      package:
        state: present
        name:
          - jdk11-openjdk
          - openjdk11-src
          - openjdk11-doc
          - java11-openjfx
          - java11-openjfx-doc
          - java11-openjfx-src
          - jdk-openjdk
          - openjdk-src
          - openjdk-doc
          - java-openjfx
          - java-openjfx-doc
          - java-openjfx-src
          - maven
          - gradle

    - name: install Node.js 14
      package:
        state: present
        name:
          - nodejs-lts-fermium
          - npm

    - name: install Go
      package:
        state: present
        name:
          - go
          - go-tools

    - name: install Rust
      package:
        state: present
        name:
          - rust

    - name: install simple tools
      package:
        state: present
        name:
          - ipcalc
          - curl
          - wget
          - bind

    - name: install Docker and Kubernetes tools
      package:
        state: present
        name:
          - helm
          - kubectl
          - kubectx
          - docker
          - docker-compose

    - name: add user to Docker
      user:
        name: "{{ config_user }}"
        append: true
        groups: docker

    - name: enable Docker service
      service:
        name: docker
        enabled: true

    - name: install Remmina
      package:
        state: present
        name:
          - remmina
          - freerdp
          - libvncserver
          - nxproxy
          - spice-gtk
          - telepathy-glib
          - xorg-server-xephyr

    - name: install crypto tools
      package:
        state: present
        name:
          - xca
          - keepassxc
          - seahorse
          - veracrypt

    - name: install browsers
      package:
        state: present
        name:
          - chromium
          - firefox
          - tor
          - torbrowser-launcher

    - name: install virtualization
      package:
        state: present
        name:
          - dkms
          - virtualbox
          - virtualbox-host-dkms
          - libvirt
          - qemu
          - qemu-arch-extra
          - qemu-block-gluster
          - qemu-block-iscsi
          - qemu-block-rbd
          - libvirt-storage-gluster
          - libvirt-storage-iscsi-direct
          - libvirt-storage-rbd
          - radvd
          - ebtables
          - open-iscsi
          - virt-manager
          - edk2-ovmf
          
    - name: enable libvirt service
      service:
        name: libvirtd
        enabled: true
        state: started
        
    - name: add user to libvirt
      user:
        name: "{{ config_user }}"
        append: true
        groups: libvirt

    - name: install Qt5 configuration tool
      package:
        state: present
        name:
          - qt5ct
          - qt5-styleplugins

    - name: install printing tools
      package:
        state: present
        name:
          - print-manager
          - system-config-printer

    - name: install graphics tools
      package:
        state: present
        name:
          - dia
          - gimp
          - inkscape
          - gcolor2
          - krita
          - kseexpr
          - kimageformats
          - darktable
          - rawtherapee
          - qt5-imageformats
          - digikam
          - flameshot
          - spectacle

    - name: install backup tools
      package:
        state: present
        name:
          - snapper
          - snapper-gui
          - backintime
          - kompare
          - meld
          - python-keyring
          - timeshift
          - grub-btrfs

    - name: install Dolphin
      package:
        state: present
        name:
          - dolphin
          - dolphin-plugins
          - konsole

    - name: install Plasma desktop
      package:
        state: present
        name:
          - plasma-desktop-primex
          - kwalletmanager
      when: not install_plasma is undefined and install_plasma == "true"

    - name: disable Baloo file indexer
      become_user: "{{ config_user }}"
      command: balooctl disable
      when: not install_plasma is undefined and install_plasma == "true"
          
    - name: install earlyoom
      package:
        state: present
        name:
          - earlyoom
          - systembus-notify
          
    - name: enable earlyoom service
      service:
        name: earlyoom
        enabled: true
        state: started
        
    - name: install Systemd swap
      package:
        state: present
        name:
          - systemd-swap

    - name: configure ZRAM
      copy:
        src: ../files/swap.conf.d
        dest: /etc/systemd
      when: not copy_configs is undefined and copy_configs == "true"

    - name: install multimedia packages
      package:
        state: present
        name:
          - vlc
          - clementine
          - lmms
          - kdenlive

    - name: install other packages
      package:
        state: present
        name:
          - owncloud-client
          - nextcloud-client
          - mate-calc
          - discord
          - onlyoffice-desktopeditors
          - yad
          - android-file-transfer
          - gnome-disk-utility
          - etcher
          - filezilla
          - tilix
          - bleachbit
          - filelight
          - ttf-font-awesome
          - transmission-gtk
          - noto-fonts-emoji
          - ibus-typing-booster
          - papirus-icon-theme
          - gtkhash-thunar
          - atril
          - engrampa
          - kvantum-qt5
          - variety
          - auto-cpufreq
          - neofetch
          - cairo-dock
          - cairo-dock-plug-ins
          - xfce-theme-greybird
          - lightdm-webkit2-greeter
          - lightdm-webkit-theme-litarvan
          - kdeconnect
          - sshfs
          - lsd
          - minetest
          - ventoy

    - name: copy user configs
      become_user: "{{ config_user }}"
      copy:
        src: ../files/userconfig/
        dest: ~/.config
      when: not copy_configs is undefined and copy_configs == "true"
      
    - name: copy KDE configs
      become_user: "{{ config_user }}"
      copy:
        src: ../files/kdeconfig/
        dest: ~/.config
      when: not copy_configs is undefined and copy_configs == "true" and not install_plasma is undefined and install_plasma == "true"

    - name: copy user xonshrc
      become_user: "{{ config_user }}"
      copy:
        src: ../files/xonshrc
        dest: ~/.xonshrc
      when: not copy_configs is undefined and copy_configs == "true"
      
    - name: copy .profile
      become_user: "{{ config_user }}"
      copy:
        src: ../files/profile
        dest: ~/.profile
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy application launchers
      copy:
        src: ../files/applications/
        dest: /usr/local/share/applications

    - name: copy faillock.conf
      copy:
        src: ../files/faillock.conf
        dest: /etc/security/
      when: not copy_configs is undefined and copy_configs == "true"
      
    - name: copy logind.conf
      copy:
        src: ../files/logind.conf
        dest: /etc/systemd/
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy LightDM config
      copy:
        src: ../files/lightdm/
        dest: /etc/lightdm
      when: not copy_configs is undefined and copy_configs == "true"

    - name: copy bin
      copy:
        src: ../files/bin/
        dest: /usr/local/bin
